export const brandsData = [
    // ── يابانية
    {
        en: "Toyota", ar: "تويوتا",
        models: [
            { en: "Camry", ar: "كامري" },
            { en: "Corolla", ar: "كورولا" },
            { en: "Land Cruiser", ar: "لاند كروزر" },
            { en: "Prado", ar: "برادو" },
            { en: "Hilux", ar: "هايلكس" },
            { en: "RAV4", ar: "راف فور" },
            { en: "Yaris", ar: "ياريس" },
            { en: "Avalon", ar: "أفالون" },
            { en: "Fortuner", ar: "فورتيونر" },
            { en: "FJ Cruiser", ar: "إف جي كروزر" },
            { en: "Sequoia", ar: "سيكويا" },
            { en: "Tundra", ar: "تاندرا" },
            { en: "Sienna", ar: "سيينا" },
            { en: "Venza", ar: "فينزا" },
            { en: "C-HR", ar: "سي إتش آر" },
            { en: "Rush", ar: "راش" },
        ],
    },
    {
        en: "Lexus", ar: "لكزس",
        models: [
            { en: "LX 570", ar: "إل إكس 570" },
            { en: "LX 600", ar: "إل إكس 600" },
            { en: "GX 460", ar: "جي إكس 460" },
            { en: "RX 350", ar: "آر إكس 350" },
            { en: "ES 350", ar: "إي إس 350" },
            { en: "LS 500", ar: "إل إس 500" },
            { en: "IS 300", ar: "آي إس 300" },
            { en: "NX 350", ar: "إن إكس 350" },
            { en: "UX 250h", ar: "يو إكس 250h" },
            { en: "LC 500", ar: "إل سي 500" },
        ],
    },
    {
        en: "Nissan", ar: "نيسان",
        models: [
            { en: "Patrol", ar: "باترول" },
            { en: "Altima", ar: "التيما" },
            { en: "Maxima", ar: "ماكسيما" },
            { en: "Sentra", ar: "سنترا" },
            { en: "Sunny", ar: "صني" },
            { en: "X-Trail", ar: "إكس تريل" },
            { en: "Murano", ar: "مورانو" },
            { en: "Pathfinder", ar: "باثفايندر" },
            { en: "Frontier", ar: "فرونتير" },
            { en: "Navara", ar: "نافارا" },
            { en: "Armada", ar: "أرمادا" },
            { en: "Kicks", ar: "كيكس" },
            { en: "Juke", ar: "جوك" },
            { en: "GT-R", ar: "جي تي آر" },
            { en: "Titan", ar: "تيتان" },
        ],
    },
    {
        en: "Honda", ar: "هوندا",
        models: [
            { en: "Accord", ar: "أكورد" },
            { en: "Civic", ar: "سيفيك" },
            { en: "CR-V", ar: "سي آر في" },
            { en: "Pilot", ar: "بايلوت" },
            { en: "HR-V", ar: "إتش آر في" },
            { en: "City", ar: "سيتي" },
            { en: "Odyssey", ar: "أوديسي" },
            { en: "Passport", ar: "باسبورت" },
            { en: "Ridgeline", ar: "ريدج لاين" },
        ],
    },
    {
        en: "Mitsubishi", ar: "ميتسوبيشي",
        models: [
            { en: "Pajero", ar: "باجيرو" },
            { en: "Montero", ar: "مونتيرو" },
            { en: "Outlander", ar: "أوتلاندر" },
            { en: "Eclipse Cross", ar: "إكليبس كروس" },
            { en: "L200", ar: "إل 200" },
            { en: "ASX", ar: "أيه إس إكس" },
            { en: "Galant", ar: "غالانت" },
        ],
    },
    {
        en: "Mazda", ar: "مازدا",
        models: [
            { en: "Mazda3", ar: "مازدا 3" },
            { en: "Mazda6", ar: "مازدا 6" },
            { en: "CX-3", ar: "سي إكس 3" },
            { en: "CX-5", ar: "سي إكس 5" },
            { en: "CX-9", ar: "سي إكس 9" },
            { en: "CX-30", ar: "سي إكس 30" },
            { en: "MX-5", ar: "إم إكس 5" },
            { en: "BT-50", ar: "بي تي 50" },
        ],
    },
    {
        en: "Suzuki", ar: "سوزوكي",
        models: [
            { en: "Vitara", ar: "فيتارا" },
            { en: "Swift", ar: "سويفت" },
            { en: "Jimny", ar: "جيمني" },
            { en: "Ertiga", ar: "إيرتيغا" },
            { en: "Ciaz", ar: "سياز" },
            { en: "Baleno", ar: "بالينو" },
            { en: "S-Cross", ar: "إس كروس" },
        ],
    },
    {
        en: "Subaru", ar: "سوبارو",
        models: [
            { en: "Outback", ar: "أوتباك" },
            { en: "Forester", ar: "فورستر" },
            { en: "Impreza", ar: "إمبريزا" },
            { en: "Legacy", ar: "ليغاسي" },
            { en: "XV", ar: "إكس في" },
            { en: "BRZ", ar: "بي آر زد" },
        ],
    },
    {
        en: "Infiniti", ar: "إنفينيتي",
        models: [
            { en: "QX80", ar: "كيو إكس 80" },
            { en: "QX60", ar: "كيو إكس 60" },
            { en: "QX50", ar: "كيو إكس 50" },
            { en: "Q50", ar: "كيو 50" },
            { en: "Q60", ar: "كيو 60" },
            { en: "Q70", ar: "كيو 70" },
        ],
    },
    // ── كورية
    {
        en: "Hyundai", ar: "هيونداي",
        models: [
            { en: "Elantra", ar: "إلنترا" },
            { en: "Sonata", ar: "سوناتا" },
            { en: "Tucson", ar: "توسان" },
            { en: "Santa Fe", ar: "سانتا في" },
            { en: "Palisade", ar: "باليسيد" },
            { en: "Creta", ar: "كريتا" },
            { en: "Accent", ar: "أكسنت" },
            { en: "Staria", ar: "ستاريا" },
            { en: "i10", ar: "آي 10" },
            { en: "i30", ar: "آي 30" },
            { en: "Veloster", ar: "فيلوستر" },
            { en: "Genesis", ar: "جينيسيس" },
            { en: "H-1", ar: "إتش 1" },
        ],
    },
    {
        en: "Kia", ar: "كيا",
        models: [
            { en: "Sportage", ar: "سبورتاج" },
            { en: "Sorento", ar: "سورنتو" },
            { en: "Telluride", ar: "تيلورايد" },
            { en: "Carnival", ar: "كارنيفال" },
            { en: "Stinger", ar: "ستينغر" },
            { en: "K5", ar: "كيه 5" },
            { en: "Seltos", ar: "سيلتوس" },
            { en: "Cerato", ar: "سيراتو" },
            { en: "Picanto", ar: "بيكانتو" },
            { en: "EV6", ar: "إي في 6" },
            { en: "Niro", ar: "نيرو" },
        ],
    },
    {
        en: "Genesis", ar: "جينيسيس",
        models: [
            { en: "G70", ar: "جي 70" },
            { en: "G80", ar: "جي 80" },
            { en: "G90", ar: "جي 90" },
            { en: "GV70", ar: "جي في 70" },
            { en: "GV80", ar: "جي في 80" },
            { en: "GV60", ar: "جي في 60" },
        ],
    },
    // ── ألمانية
    {
        en: "Mercedes-Benz", ar: "مرسيدس بنز",
        models: [
            { en: "A-Class", ar: "إيه كلاس" },
            { en: "C-Class", ar: "سي كلاس" },
            { en: "E-Class", ar: "إي كلاس" },
            { en: "S-Class", ar: "إس كلاس" },
            { en: "CLA", ar: "سي إل إيه" },
            { en: "GLA", ar: "جي إل إيه" },
            { en: "GLC", ar: "جي إل سي" },
            { en: "GLE", ar: "جي إل إي" },
            { en: "GLS", ar: "جي إل إس" },
            { en: "G-Class", ar: "جي كلاس" },
            { en: "AMG GT", ar: "إيه إم جي جي تي" },
            { en: "EQS", ar: "إي كيو إس" },
            { en: "EQE", ar: "إي كيو إي" },
        ],
    },
    {
        en: "BMW", ar: "بي إم دبليو",
        models: [
            { en: "1 Series", ar: "الفئة الأولى" },
            { en: "2 Series", ar: "الفئة الثانية" },
            { en: "3 Series", ar: "الفئة الثالثة" },
            { en: "4 Series", ar: "الفئة الرابعة" },
            { en: "5 Series", ar: "الفئة الخامسة" },
            { en: "7 Series", ar: "الفئة السابعة" },
            { en: "X1", ar: "إكس 1" },
            { en: "X3", ar: "إكس 3" },
            { en: "X5", ar: "إكس 5" },
            { en: "X6", ar: "إكس 6" },
            { en: "X7", ar: "إكس 7" },
            { en: "M3", ar: "إم 3" },
            { en: "M5", ar: "إم 5" },
            { en: "i4", ar: "آي 4" },
            { en: "iX", ar: "آي إكس" },
            { en: "M8", ar: "إم 8" },
        ],
    },
    {
        en: "Audi", ar: "أودي",
        models: [
            { en: "A3", ar: "إيه 3" },
            { en: "A4", ar: "إيه 4" },
            { en: "A6", ar: "إيه 6" },
            { en: "A8", ar: "إيه 8" },
            { en: "Q3", ar: "كيو 3" },
            { en: "Q5", ar: "كيو 5" },
            { en: "Q7", ar: "كيو 7" },
            { en: "Q8", ar: "كيو 8" },
            { en: "TT", ar: "تي تي" },
            { en: "R8", ar: "آر 8" },
            { en: "RS6", ar: "آر إس 6" },
            { en: "e-tron", ar: "إي ترون" },
        ],
    },
    {
        en: "Porsche", ar: "بورشه",
        models: [
            { en: "911", ar: "911" },
            { en: "Cayenne", ar: "كايين" },
            { en: "Macan", ar: "ماكان" },
            { en: "Panamera", ar: "باناميرا" },
            { en: "Taycan", ar: "تايكان" },
            { en: "Boxster", ar: "بوكستر" },
            { en: "Cayman", ar: "كايمان" },
        ],
    },
    {
        en: "Volkswagen", ar: "فولكسفاغن",
        models: [
            { en: "Golf", ar: "جولف" },
            { en: "Passat", ar: "باسات" },
            { en: "Tiguan", ar: "تيغوان" },
            { en: "Touareg", ar: "توارق" },
            { en: "Polo", ar: "بولو" },
            { en: "Arteon", ar: "أرتيون" },
            { en: "ID.4", ar: "آي دي 4" },
            { en: "Jetta", ar: "جيتا" },
        ],
    },
    // ── أمريكية
    {
        en: "Ford", ar: "فورد",
        models: [
            { en: "F-150", ar: "إف 150" },
            { en: "Explorer", ar: "إكسبلورر" },
            { en: "Expedition", ar: "إكسبديشن" },
            { en: "Mustang", ar: "موستانج" },
            { en: "Edge", ar: "إيدج" },
            { en: "Escape", ar: "إسكيب" },
            { en: "Ranger", ar: "رينجر" },
            { en: "Bronco", ar: "برونكو" },
            { en: "Maverick", ar: "مافريك" },
        ],
    },
    {
        en: "Chevrolet", ar: "شيفروليه",
        models: [
            { en: "Tahoe", ar: "تاهو" },
            { en: "Suburban", ar: "سوبربان" },
            { en: "Silverado", ar: "سيلفرادو" },
            { en: "Camaro", ar: "كامارو" },
            { en: "Malibu", ar: "ماليبو" },
            { en: "Equinox", ar: "إكونيكس" },
            { en: "Blazer", ar: "بليزر" },
            { en: "Traverse", ar: "ترافيرس" },
            { en: "Colorado", ar: "كولورادو" },
            { en: "Captiva", ar: "كابتيفا" },
            { en: "Trailblazer", ar: "تريلبليزر" },
        ],
    },
    {
        en: "GMC", ar: "جي إم سي",
        models: [
            { en: "Yukon", ar: "يوكون" },
            { en: "Sierra", ar: "سييرا" },
            { en: "Canyon", ar: "كانيون" },
            { en: "Terrain", ar: "تيرين" },
            { en: "Acadia", ar: "أكاديا" },
            { en: "Envoy", ar: "إنفوي" },
            { en: "Jimmy", ar: "جيمي" },
        ],
    },
    {
        en: "Cadillac", ar: "كاديلاك",
        models: [
            { en: "Escalade", ar: "إسكاليد" },
            { en: "CT5", ar: "سي تي 5" },
            { en: "XT4", ar: "إكس تي 4" },
            { en: "XT5", ar: "إكس تي 5" },
            { en: "XT6", ar: "إكس تي 6" },
            { en: "Lyriq", ar: "ليريك" },
        ],
    },
    {
        en: "Jeep", ar: "جيب",
        models: [
            { en: "Wrangler", ar: "رانجلر" },
            { en: "Grand Cherokee", ar: "جراند شيروكي" },
            { en: "Cherokee", ar: "شيروكي" },
            { en: "Compass", ar: "كومباس" },
            { en: "Gladiator", ar: "جلاديتور" },
            { en: "Renegade", ar: "رينيجيد" },
            { en: "Avenger", ar: "أفينجر" },
        ],
    },
    {
        en: "Dodge", ar: "دودج",
        models: [
            { en: "Challenger", ar: "تشالنجر" },
            { en: "Charger", ar: "تشارجر" },
            { en: "Durango", ar: "دورانجو" },
            { en: "Ram 1500", ar: "رام 1500" },
        ],
    },
    {
        en: "Ram", ar: "رام",
        models: [
            { en: "1500", ar: "1500" },
            { en: "2500", ar: "2500" },
            { en: "3500", ar: "3500" },
            { en: "ProMaster", ar: "برو ماستر" },
        ],
    },
    {
        en: "Lincoln", ar: "لينكولن",
        models: [
            { en: "Navigator", ar: "نافيغيتور" },
            { en: "Aviator", ar: "أفياتور" },
            { en: "Corsair", ar: "كورسير" },
            { en: "Nautilus", ar: "نوتيلوس" },
        ],
    },
    // ── بريطانية
    {
        en: "Land Rover", ar: "لاند روفر",
        models: [
            { en: "Defender", ar: "ديفندر" },
            { en: "Discovery", ar: "ديسكفري" },
            { en: "Discovery Sport", ar: "ديسكفري سبورت" },
            { en: "Range Rover", ar: "رينج روفر" },
            { en: "Range Rover Sport", ar: "رينج روفر سبورت" },
            { en: "Range Rover Evoque", ar: "رينج روفر إيفوك" },
            { en: "Range Rover Velar", ar: "رينج روفر فيلار" },
        ],
    },
    {
        en: "Jaguar", ar: "جاغوار",
        models: [
            { en: "F-PACE", ar: "إف بيس" },
            { en: "E-PACE", ar: "إي بيس" },
            { en: "I-PACE", ar: "آي بيس" },
            { en: "XE", ar: "إكس إي" },
            { en: "XF", ar: "إكس إف" },
            { en: "XJ", ar: "إكس جي" },
            { en: "F-TYPE", ar: "إف تايب" },
        ],
    },
    {
        en: "MINI", ar: "ميني",
        models: [
            { en: "Cooper", ar: "كوبر" },
            { en: "Countryman", ar: "كونتريمان" },
            { en: "Clubman", ar: "كلابمان" },
            { en: "Convertible", ar: "كونفيرتبل" },
            { en: "Paceman", ar: "باسمان" },
        ],
    },
    {
        en: "Bentley", ar: "بنتلي",
        models: [
            { en: "Continental GT", ar: "كونتيننتال جي تي" },
            { en: "Bentayga", ar: "بينتايغا" },
            { en: "Flying Spur", ar: "فلاينج سبير" },
            { en: "Mulsanne", ar: "مولسان" },
        ],
    },
    {
        en: "Rolls-Royce", ar: "رولز رويس",
        models: [
            { en: "Ghost", ar: "غوست" },
            { en: "Phantom", ar: "فانتوم" },
            { en: "Cullinan", ar: "كولينان" },
            { en: "Wraith", ar: "ريث" },
            { en: "Dawn", ar: "دوون" },
            { en: "Spectre", ar: "سبيكتر" },
        ],
    },
    // ── إيطالية
    {
        en: "Ferrari", ar: "فيراري",
        models: [
            { en: "Roma", ar: "روما" },
            { en: "F8 Tributo", ar: "إف 8 تريبوتو" },
            { en: "SF90", ar: "إس إف 90" },
            { en: "812", ar: "812" },
            { en: "Portofino", ar: "بورتوفينو" },
            { en: "Purosangue", ar: "بوروسانغوي" },
        ],
    },
    {
        en: "Lamborghini", ar: "لامبورغيني",
        models: [
            { en: "Huracán", ar: "أوراكان" },
            { en: "Urus", ar: "أوروس" },
            { en: "Revuelto", ar: "ريفويلتو" },
        ],
    },
    {
        en: "Maserati", ar: "مازيراتي",
        models: [
            { en: "Ghibli", ar: "غيبلي" },
            { en: "Levante", ar: "ليفانتي" },
            { en: "Quattroporte", ar: "كواتروبورتي" },
            { en: "GranTurismo", ar: "غران توريزمو" },
            { en: "MC20", ar: "إم سي 20" },
        ],
    },
    {
        en: "Alfa Romeo", ar: "ألفا روميو",
        models: [
            { en: "Giulia", ar: "جوليا" },
            { en: "Stelvio", ar: "ستيلفيو" },
            { en: "Tonale", ar: "تونالي" },
        ],
    },
    // ── فرنسية / سويدية
    {
        en: "Peugeot", ar: "بيجو",
        models: [
            { en: "208", ar: "208" },
            { en: "308", ar: "308" },
            { en: "2008", ar: "2008" },
            { en: "3008", ar: "3008" },
            { en: "5008", ar: "5008" },
        ],
    },
    {
        en: "Renault", ar: "رينو",
        models: [
            { en: "Clio", ar: "كليو" },
            { en: "Megane", ar: "ميغان" },
            { en: "Duster", ar: "داستر" },
            { en: "Koleos", ar: "كوليوس" },
            { en: "Arkana", ar: "أركانا" },
        ],
    },
    {
        en: "Volvo", ar: "فولفو",
        models: [
            { en: "XC40", ar: "إكس سي 40" },
            { en: "XC60", ar: "إكس سي 60" },
            { en: "XC90", ar: "إكس سي 90" },
            { en: "S60", ar: "إس 60" },
            { en: "S90", ar: "إس 90" },
            { en: "V60", ar: "في 60" },
            { en: "EX90", ar: "إي إكس 90" },
        ],
    },
    // ── صينية
    {
        en: "Haval", ar: "هافال",
        models: [
            { en: "H6", ar: "إتش 6" },
            { en: "H9", ar: "إتش 9" },
            { en: "Jolion", ar: "جوليون" },
            { en: "F7", ar: "إف 7" },
            { en: "H2", ar: "إتش 2" },
        ],
    },
    {
        en: "BYD", ar: "بي واي دي",
        models: [
            { en: "Han", ar: "هان" },
            { en: "Tang", ar: "تانج" },
            { en: "Song Pro", ar: "سونج برو" },
            { en: "Atto 3", ar: "أتو 3" },
            { en: "Seal", ar: "سيل" },
            { en: "Dolphin", ar: "دولفين" },
        ],
    },
    {
        en: "Changan", ar: "شانجان",
        models: [
            { en: "CS75 Plus", ar: "سي إس 75 بلس" },
            { en: "CS35 Plus", ar: "سي إس 35 بلس" },
            { en: "CS55 Plus", ar: "سي إس 55 بلس" },
            { en: "Alsvin", ar: "ألسفين" },
            { en: "UNI-T", ar: "يوني تي" },
        ],
    },
    {
        en: "Geely", ar: "جيلي",
        models: [
            { en: "Coolray", ar: "كولراي" },
            { en: "Tugella", ar: "تيوجيلا" },
            { en: "Atlas", ar: "أتلاس" },
            { en: "Emgrand", ar: "إمجراند" },
        ],
    },
    {
        en: "JAC", ar: "جاك",
        models: [
            { en: "J7", ar: "جيه 7" },
            { en: "S3", ar: "إس 3" },
            { en: "S7", ar: "إس 7" },
            { en: "T8", ar: "تي 8" },
        ],
    },
    // ── أخرى
    {
        en: "Tesla", ar: "تيسلا",
        models: [
            { en: "Model S", ar: "موديل إس" },
            { en: "Model 3", ar: "موديل 3" },
            { en: "Model X", ar: "موديل إكس" },
            { en: "Model Y", ar: "موديل واي" },
            { en: "Cybertruck", ar: "سايبرتراك" },
        ],
    },
];

brandsData.sort((a, b) => a.ar.localeCompare(b.ar, "ar"));

